default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: api_development

test:
  <<: *default
  database: api_test

production:
  <<: *default
  database: hippo_alpha
  username: <%= ENV['DB_USERNAME_PROD'] %>
  host: <%= ENV['DB_HOST_PROD'] %>
  password: <%= ENV['DB_PASSWORD_PROD'] %>
  ssl_mode: verify_identity
  sslca: "/etc/ssl/certs/ca-certificates.crt"
